Merge branch 'devel-andreaM' into devel-models

diff --git a/lib/archive/Makefile.loc b/lib/archive/Makefile.loc
--- a/lib/archive/Makefile.loc
+++ b/lib/archive/Makefile.loc
@@ -2,46 +2,51 @@
 # Package List
 #
 include ./package.list
+include ./git.list
+#
 WGETFLAGS=--no-check-certificate
 #
 all: $(EXT_LIBS)
 #
-# Libraries
+# Libraries (GIT + archives)
 #
-Ydriver:
-	@+TARBALL="$(tarball_Ydriver)"  ; LIB="YDRIVER"; $(getsrc)
+Ylib:
+	@+URL="$(url_Ylib)"  ;  GBRANCH="$(branch_Ylib)"  ;  GIT="$(git_Ylib)"; LIB="$(pkgname_Ylib)"; $(getsrc_git); $(call link_it,"yambo")
+#
+# Libraries (archives)
+#
 yaml:
-	@+TARBALL="$(tarball_yaml)"     ; LIB="YAML"; $(getsrc)
+	@+URL="$(url_yaml)"     ; LIB="$(pkgname_yaml)"; $(getsrc)
 futile:
-	@+TARBALL="$(tarball_futile)"   ; LIB="FUTILE"; $(getsrc)
-iotk: 
-	@+TARBALL="$(tarball_iotk)"     ; LIB="IOTK"; $(getsrc)
+	@+URL="$(url_futile)"   ; LIB="$(pkgname_futile)"; $(getsrc)
+iotk:
+	@+URL="$(url_iotk)"     ; LIB="$(pkgname_iotk)"; $(getsrc)
 hdf5:
-	@+TARBALL="$(tarball_hdf5)"     ; LIB="HDF5"; $(getsrc)
+	@+URL="$(url_hdf5)"     ; LIB="$(pkgname_hdf5)"; $(getsrc)
 netcdf:
-	@+TARBALL="$(tarball_netcdf)"   ; LIB="NETCDF"; $(getsrc)
+	@+URL="$(url_netcdf)"   ; LIB="$(pkgname_netcdf)"; $(getsrc)
 netcdff:
-	@+TARBALL="$(tarball_netcdff)"  ; LIB="NETCDFF"; $(getsrc)
+	@+URL="$(url_netcdff)"  ; LIB="$(pkgname_netcdff)"; $(getsrc)
 pnetcdf:
-	@+TARBALL="$(tarball_pnetcdf)"  ; LIB="PNETCDF"; $(getsrc)
+	@+URL="$(url_pnetcdf)"  ; LIB="$(pkgname_pnetcdf)"; $(getsrc)
 etsf_io:
-	@+TARBALL="$(tarball_etsf_io)"  ; LIB="ETSF_IO"; $(getsrc)
+	@+URL="$(url_etsf_io)"  ; LIB="$(pkgname_etsf_io)"; $(getsrc)
 libxc:
-	@+TARBALL="$(tarball_libxc)"    ; LIB="LIBXC"; $(getsrc)
+	@+URL="$(url_libxc)"    ; LIB="$(pkgname_libxc)"; $(getsrc)
 lapack:
-	@+TARBALL="$(tarball_lapack)"   ; LIB="LAPACK"; $(getsrc)
+	@+URL="$(url_lapack)"   ; LIB="$(pkgname_lapack)"; $(getsrc)
 blacs:
-	@+TARBALL="$(tarball_blacs)"    ; LIB="BLACS"; $(getsrc)
+	@+URL="$(url_blacs)"    ; LIB="$(pkgname_blacs)"; $(getsrc)
 scalapack:
-	@+TARBALL="$(tarball_scalapack)"; LIB="SCALAPACK"; $(getsrc)
+	@+URL="$(url_scalapack)"; LIB="$(pkgname_scalapack)"; $(getsrc)
 petsc:
-	@+TARBALL="$(tarball_petsc)"    ; LIB="PETSC"; $(getsrc)
+	@+URL="$(url_petsc)"    ; LIB="$(pkgname_petsc)"; $(getsrc)
 slepc:
-	@+TARBALL="$(tarball_slepc)"    ; LIB="SLEPC"; $(getsrc)
+	@+URL="$(url_slepc)"    ; LIB="$(pkgname_slepc)"; $(getsrc)
 fftw:
-	@+TARBALL="$(tarball_fftw)"     ; LIB="FFTW"; $(getsrc)
+	@+URL="$(url_fftw)"     ; LIB="$(pkgname_fftw)"; $(getsrc)
 fftqe:
-	@+TARBALL="$(tarball_fftqe)"    ; LIB="FFTW"; $(getsrc)
+	@+URL="$(url_fftqe)"    ; LIB="$(pkgname_fftqe)"; $(getsrc)
 #
 # cleaning
 #
@@ -49,7 +54,7 @@ clean: clean_all
 #
 clean_all:
 	if test ! -e keep-extlibs-stamp ; then \
-          if test -s $(tarball_Ydriver)  && test "$(keep_Ydriver)"   != "yes" ;  then rm $(tarball_Ydriver)    ; fi ; \
+          if test -s $(tarball_Ylib)     && test "$(keep_Ylib)"      != "yes" ;  then rm -fr $(pkgname_Ylib)* ../yambo ; fi ; \
           if test -s $(tarball_libxc)    && test "$(keep_libxc)"     != "yes" ;  then rm $(tarball_libxc)     ; fi ; \
           if test -s $(tarball_iotk)     && test "$(keep_iotk)"      != "yes" ;  then rm $(tarball_iotk)      ; fi ; \
           if test -s $(tarball_netcdf)   && test "$(keep_netcdf)"    != "yes" ;  then rm $(tarball_netcdf)    ; fi ; \
@@ -69,14 +74,40 @@ clean_all:
 	fi
 #
 define getsrc
-if [ -x $(shell which wget) ] && [ "$(shell which wget)" != "" ] ; then \
- wget $(WGETFLAGS) -c -O $$TARBALL https://github.com/yambo-code/yambo-libraries/raw/master/external/$$TARBALL ; \
-elif [ -x $(shell which curl) ] && [ "$(shell which curl)" != "" ] ; then \
- curl -L --progress-bar -o $$TARBALL https://github.com/yambo-code/yambo-libraries/raw/master/external/$$TARBALL ; \
-fi ; \
-if test ! -s $$TARBALL ; then \
-echo "*** Unable to download $$LIB. Test whether curl or wget is installed and working," ; \
-echo "*** if you have direct access to the internet." ; \
-echo "*** If not, copy $$TARBALL into extlibs/archive/" ; \
-fi
+ if test ! -s $$LIB".tar.gz" ; then \
+  echo -n "getting "$$LIB "..."; \
+  if [ -x $(shell which wget) ] && [ "$(shell which wget)" != "" ] ; then \
+   wget $(WGETFLAGS) -O $$LIB".tar.gz" $$URL ; \
+  elif [ -x $(shell which curl) ] && [ "$(shell which curl)" != "" ] ; then \
+   curl -L --progress-bar -o $$LIB".tar.gz" $$URL ; \
+  fi ; \
+  if test ! -s $$LIB".tar.gz" ; then \
+   echo "*** Unable to download $$LIB. Test whether curl or wget is installed and working," ; \
+   echo "*** if you have direct access to the internet." ; \
+   echo "*** If not, copy $$LIB".tar.gz" into extlibs/archive/" ; \
+  fi; \
+ fi
+endef
+#
+define getsrc_git
+ if test ! -s $$LIB".tar.gz" && test ! -d $$LIB ; then \
+  echo -n "getting "$$LIB "..."; \
+  if [ ! "$$GBRANCH" = "none" ] ; then \
+   echo " via $$GIT" ; \
+   if [ ! -d $$LIB ]; then git clone $$GIT $$LIB; fi ; \
+   cd $$LIB ; git checkout $$GBRANCH ; cd ../ ; \
+  else \
+   echo "via wget" ; \
+   if [ -x $(shell which wget) ] && [ "$(shell which wget)" != "" ] ; then \
+    wget $(WGETFLAGS) -O $$LIB".tar.gz" $$URL ; \
+   elif [ -x $(shell which curl) ] && [ "$(shell which curl)" != "" ] ; then \
+    curl -L --progress-bar -o $$LIB".tar.gz" $$URL ; \
+   fi \
+  fi;\
+ fi
+endef
+#
+define link_it
+ if test -s $$LIB".tar.gz" ; then gunzip < $$LIB".tar.gz" | ../../config/missing --run tar xf - ; fi;\
+ if ! test -d ../$(1); then ln -s $(PWD)/$$LIB ../$(1);fi
 endef
